"""empty message

Revision ID: 6ee7b3a439ed
Revises: 
Create Date: 2020-07-15 18:10:37.192261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee7b3a439ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EscooterAllinfo',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bmid', sa.String(), nullable=True),
    sa.Column('car_type', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('UsedorNot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('FONLoc',
    sa.Column('loc', sa.String(), nullable=False),
    sa.Column('longnla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('loc')
    )
    op.create_table('RealtimeCarDetails',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('UsedorNot', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('RealtimeCarOrderRecord',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('CarAllinfo',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('UsedorNot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['FONLoc.loc'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('EscooterOrderRecord',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['EscooterAllinfo.item_id'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('BookingRecord',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('reserved_time', sa.Integer(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('qdid', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('reserveStatus', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bmid'], ['CarAllinfo.bmid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('QueryRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bmid'], ['CarAllinfo.bmid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReservedCarStatus',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('carAmount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bmid'], ['CarAllinfo.bmid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('OrderRecord',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('qd_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bmid'], ['CarAllinfo.bmid'], ),
    sa.ForeignKeyConstraint(['item_id'], ['CarAllinfo.item_id'], ),
    sa.ForeignKeyConstraint(['qd_id'], ['QueryRecord.id'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderRecord')
    op.drop_table('ReservedCarStatus')
    op.drop_table('QueryRecord')
    op.drop_table('BookingRecord')
    op.drop_table('EscooterOrderRecord')
    op.drop_table('CarAllinfo')
    op.drop_table('RealtimeCarOrderRecord')
    op.drop_table('RealtimeCarDetails')
    op.drop_table('FONLoc')
    op.drop_table('EscooterAllinfo')
    # ### end Alembic commands ###
